package com.bignerdranch.android.bluetoothtestbed

import java.util.*

object Constants {
    const val SERVICE_STRING = "7D2EA28A-F7BD-485A-BD9D-92AD6ECFE93E"
    val SERVICE_UUID
        get() = UUID.fromString(SERVICE_STRING)
    const val CHARACTERISTIC_ECHO_STRING = "7D2EBAAD-F7BD-485A-BD9D-92AD6ECFE93E"
    val CHARACTERISTIC_ECHO_UUID
        get() = UUID.fromString(CHARACTERISTIC_ECHO_STRING)
    const val CHARACTERISTIC_TIME_STRING = "7D2EDEAD-F7BD-485A-BD9D-92AD6ECFE93E"
    val CHARACTERISTIC_TIME_UUID
        get() = UUID.fromString(CHARACTERISTIC_TIME_STRING)
    const val CLIENT_CONFIGURATION_DESCRIPTOR_STRING = "00002902-0000-1000-8000-00805f9b34fb"
    val CLIENT_CONFIGURATION_DESCRIPTOR_UUID
        get() = UUID.fromString(CLIENT_CONFIGURATION_DESCRIPTOR_STRING)
    const val CLIENT_CONFIGURATION_DESCRIPTOR_SHORT_ID = "2902"
    const val SCAN_PERIOD: Long = 5000
}